### ISSUE TITLE
Question: Possible to use as part of postcss-loader chain in webpack?

### ISSUE THREAD

**Issue by sgordon3** [lochstar/postcss-extract-custom-properties#1]
Saw your post on Dan Bahrami's blog article on custom css properties and it sounded great. following your link to Postcss didn't lead me to any examples of postcss plugins that return json in addition to passing the css on. In dev there is no css file to use as an input param, so the assumption is that each plugin in the chain passes the css onto the next. But how would you write the output from results?
Here's a sample rule (with postcss-extract-custom-properties imported as extractcustomprops): Any pointers would be appreciated.

{
          test: /\.scss$/,
          use: [{
            loader: 'style-loader',
          }, {
            loader: 'css-loader', options: { sourcemap: true },
          }, {
            loader: 'postcss-loader',
            options: {
              plugins() {
                return [autoprefixer, extractcustomprops];
              },
            },
          }, {
            loader: 'sass-loader', options: { sourcemap: true },
          }],

**Comment by lochstar** [comment]
Hi @sgordon3, it's not currently possible to use it in this way.

I'm not sure of any other postcss plugins that generate non-css output that is then hot-loaded in a dev environment, especially since the parsing of the output JSON is up to the user. Let me know if you come across anything similar.

**Comment by sgordon3** [comment]
Hi,

Take a look at this repo. https://github.com/ezavile/postcss-typescript-css
He is generating typescript files to hold styles imported at runtime. The
idea is that you want the generation of the JSON files at build time and
the parsing to happen at runtime. Otherwise all IE users would have to wait
for both the generation of the JSON and the parsing before the styles could
be loaded.

I was able to combine both concepts, but currently the importing of the
JSON is causing webpack to rebuild multiple times. The end result does
work, but there are multiple rebuilds in the process. It maybe the timing
of the loading of the json is happening before the creation and webpack is
rebuilding as the files are written.

**Comment by lochstar** [comment]
Sounds like you're on the right track. It's not a priority for me at the moment but if you can work it out and submit a PR then I'll take a look. Good luck!
